### ISSUE TITLE
clientid_prefixes support?

### ISSUE THREAD

**Issue by stela5** [raphaelcohn/bish-bosh#3]
Does bish-bosh support/implement something like [clientid_prefixes](http://www-01.ibm.com/support/knowledgecenter/SS9D84_1.0.0/com.ibm.mm.tc.doc/tc60914_.htm%23tc60914___cidp)?  The conceptual idea is to connect to test.mosquitto.org on port 8883 (TLS) and use this feature to limit pubsub communication to a limited set of computers that share this (presumably long and randomized) shared "secret".  Essentially, a poor-man's less-secure version of PSK...

**Comment by raphaelcohn** [comment]
`bish-bosh` is a client, not a broker, so you can use whatever clientids you want...

**Comment by stela5** [comment]
Thanks!
